### ISSUE TITLE
[Discussion] PoW separate from hooknodes?

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/brokernode#117]
Transactions will appear on the tangle quicker if the trytes array is broadcast on multiple iota nodes (can be brokernodes, hooknodes, or public iota nodes that allow use of the broadcastTransactions method).  Who will call other nodes and ask them to broadcast the transaction?  Will we use our own hooknodes or attempt to use public nodes? 

Discuss/Decide:  Have the Go attachToTangle called on the hooknodes, or separate this out to a PoW machine?  

Pros of separating to separate PoW machines:
* Will only need about 10 of these and can get rid of lots of our hooknodes
* Since we don’t need many, can make them very powerful
* Separation of concerns
* We can also delegate the PoW on PaaS or FaaS instances, thus adding scalability to the whole system.

Cons:  
* “Centralized” 
* More http requests
* Major change to the protocol and the economic structure of the system
* Would have to update a lot of old code

**Comment by rfornea** [comment]
>Transactions will appear on the tangle quicker if the trytes array is broadcast on multiple iota nodes (can be brokernodes, hooknodes, or public iota nodes that allow use of the broadcastTransactions method). Who will call other nodes and ask them to broadcast the transaction? Will we use our own hooknodes or attempt to use public nodes?   

I think we should use our own nodes, and I think we can probably just use our hooknodes.  I think it might make the most sense for the broker to grab an array of X hooknodes and send those IPs along with the request to the hooknode to perform attachToTangle.  The only disadvantage I see is that I don't know if there is any way to actually verify that the hooknodes did the broadcasting.  Let's say 9 of them broadcasted it and 1 of them didn't, because it is selfish.  We would not have any way of knowing that the selfish one didn't do the broadcast.  This might not be an issue as long as most of them are doing the broadcast, but it's something to consider.

**Comment by AaronVasquez** [comment]
What's the purpose of sending the request to multuple hooknodes? If it's just speed, it might not be worth the added complexity. It's important to know which hooknodes aren't acting according to the protocol, so they can be punished via reputation system.

**Comment by AaronVasquez** [comment]
@rfornea Do you think we can close this? I don't think we are still considering separating this out are we?

**Comment by rfornea** [comment]
@AaronVasquez   I think Andrew still likes this idea, but either way, it would be quite a ways in the future.  I think we can close this.
