### ISSUE TITLE
Build the data map asynchronously so we don't get timeouts

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#147]
Currently the client waits for the broker to finish building the data map, which causes the client to experience timeouts with file sizes over a certain size.  The bottleneck should not be the actual calculation of the hashes, but rather storing them to the db.  

Building the data map asynchronously could have the following issues:
Andrew:  The big problem with this one is that the beta broker is starting from the end, thus it would start well after the alpha broker and have to catch up.

Here are some thoughts from Telegram of how to approach this problem:  
Bruno Block admin:
it should be async
send to DB but dont wait for confirmation
Automyr:
We could hash to the end and then build the datamap as the upload 
progresses
Bruno Block admin:
bulk INSERT statements usually help
Rebel:
Ok
Bruno Block admin:
I think INSERT IGNORE makes the difference?
"Automyr: We could hash to the end and then build the datamap as the upload pr…"
This makes sense
the datamap should get built as chunks are received   

The goal for this task is to implement something that satisfies the following:
-build data map asynchronously so client can go ahead and start sending chunks rather than waiting for the broker to be done saving the data map to its DB
-do this in such a way that the beta broker is not penalized relative to the alpha broker

This is so that:
-we can send files of any size without timeout issues due to data map building

Priority:  Medium

**Comment by automyr** [comment]
The idea I had to hash to the end without saving it to the db would speed things up, but it's not a panacea. Due to not having an inverse hashing function, we cannot get the (n-1) iteration from the n-th one. 

This means that our best option is probably a combination of making an async process to build the datamap and another one that will rush to the end of the datamap to start the upload as soon as possible.

For example, the second process could just hash as fast as possible till it gets to the last 100 iterations, and then start inserting those into the db. I believe our current bottleneck lies in inserting each iteration into the mariadb database, so this could help us make the system more scalable.

The Beta broker will always be at a disadvantage over the Alpha due to how hash functions work unless the client already builds the entire datamap and sends it along with the file - or we make an intermediary service that does this before starting the upload.

**Comment by AaronVasquez** [comment]
If we try to speed this up, it will always be a race condition. A real solution would be to have a fallback when a chunk is sent and the datamap is not complete. Speeding things up would just reduce the frequency of this happening.

A possible solution is to check if the datamap is ready for a chunk. If not, save it in the DB and have the a cronjob (separate, more frequent one) retry at a later time.

**Comment by rfornea** [comment]
@AaronVasquez   That sounds like a good solution to me.

**Comment by AaronVasquez** [comment]
@rfornea @pzhao5 our architecture has changed quite a bit since this issue was created. Do we already generate the datamap async? If not this would be relatively simple to do since we process chunks in cron jobs right?

**Comment by rfornea** [comment]
There may not be any value in making any large changes to what we are doing with the datamaps until we're ready to start putting batches of chunks in temp files rather than in rows in the DB.  

But yes, this should be easy to do.  We could take it a step further and write incoming chunk data to some kind of /chunksBeingStaged directory and have a cron task building the datamap and then picking up these chunks that are in the process of being sent by the client, and doing whatever it needs to do to them, before creating new files in some different directory for chunks that are ready for attachment to the tangle.

**Comment by AaronVasquez** [comment]
@rfornea do you think this is something @pzhao5 should work on? Do you know of any more urgent tasks?

**Comment by rfornea** [comment]
@AaronVasquez We might should still work on this, but I noticed a more pressing issue yesterday.  Downloads seem to be scrambled sometimes.

**Comment by rfornea** [comment]
Not entirely sure if we need this.  Just gonna stick it in Icebox for now.

**Comment by rfornea** [comment]
Update on this.  

`BuildDataMaps` can take a while for large files, so we need to be able to wrap it in a `go func(){}()` so tht the client doesn't have to wait (possibly risking a timeout).  Meanwhile, `ProcessAndStoreChunkData`, which is what receives the "message" data, expects the chunk to already be in the data map.  Currently this is always true since `BuildDataMaps` does not happen asynchronously.  We need to modify `ProcessAndStoreChunkData` so that the functionality will still work even if the data_map row is not there yet.  

Possible options:
-go ahead and create the K:V pair in badger with the chunk's message data, without checking if a chunk already exists with that genesis hash and chunk idx.  Then add another method that will bulk-modify any chunks for which there is already a K:V pair in badger to a message status of `MsgStatusUploadedHaveNotEncoded`.  If we set a TTL on the badger data, it will automatically get garbage-collected if `BuildDataMaps` has failed.  
-change `ProcessAndStoreChunkData` to where it simply adds the chunk data to some new table such as "pending_chunks".  Then add a new job/task that will run that will perform the functionality that `ProcessAndStoreChunkData` currently fulfills, and delete chunks from "pending_chunks" when ready.  A disadvantage of this approach is that we'd be storing the message field in mysql again, however briefly.

**Comment by pzhao5** [comment]
So, in this case, we have Alpha and Beta.
Client will put half of the data into Alpha and Beta evenly? Since both have not finished building the dataMap and burry the treasure.

For your first option, you had to be careful to handle the case with treasure. For example, if you have a range of 0 to 10.
And treasure is in 3 and 7.
When you insert into Badger, you need to correctly offset it.

I think Option A is better than Option B, since querying/update the table could potential lock the entirely table and lead more performance impact.

However, for Option A, we still need to implement this GC to clean up Badger data

**Comment by rfornea** [comment]
I lean towards option A as well.  There's other things we'll need to consider too--we will have to make sure the garbage collection occurs long enough after we have had time to back everything up to S3.  

The good thing is, we will at least already know the treasure indexes by the time the client sends the message data, so we should be able to offset it.

**Comment by automyr** [comment]
For Option A, there's another possible optimization we can make once we get to rev2: as treasure chunks will be fixed to the first chunk of each sector, we can use the hash (or the address) as the key in Badger.

This allows us to get rid of one of the columns on the mysql table, and more importantly, also a large number of queries which are needed to keep the table updated. With this, the broker could go down the datamap and if it needs a specific chunk, it would just query Badger with the hash or address, without needing to read a specific (different) key from the table.

**Comment by rfornea** [comment]
This is done
