### ISSUE TITLE
[Broker] Claim treasure

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/brokernode#229]
Create a new endpoint on the broker:
`POST /api/v1/treasures`
```js
// POST body
{
    receiverEthAddr: "0xThisIsTheWebsiteOwnersAddr"
    treasure: {
        genesisHash: "genesisHash",
        sectorIdx: 123,
        numChunks: 1234567, // This is the total number of chunks, not just the sector
        ethAddr: "ethAddr",
        ethKey: "0xSuperSecretKey",
    }
}
```

1. Broker needs to verify that all PoW has been done
    1. Check that the chunk has been attached recently
2. After verification, call `claim()` on smart contract.
    1. https://github.com/oysterprotocol/smartcontract/blob/master/OysterPearl.sol#L228
    2. The broker will provide the gas needed from its own ETH wallet

**Comment by AaronVasquez** [comment]
@tenisakb I'm re-assigning this to you. If you have questions about interacting with the smart contract, please ask @Astor. He is working on setting up the ethereum client on the broker.

**Comment by rfornea** [comment]
@tenisakb @AaronVasquez   I think within the treasure body we are also going to have to include the file size or the number of chunks.  Otherwise, the broker won't know when to stop building the data map.  

This won't really matter for any sectors except the last one.  For example if the broker needs to verify sector 2, there's no reason for it to make the data map past sector 2.  But let's say it's sector 3 and sector 3 is the last one and only has 400,000 hashes, the broker would need to know to stop building the datamap in the 3rd sector after 400,000 hashes.

**Comment by AaronVasquez** [comment]
Yes, good point. I'll update the description to include `numChunks`. Since the client already has this number, no point in having the broker also calculate the offset w/ treasure again.

**Comment by pzhao5** [comment]
https://github.com/oysterprotocol/brokernode/pull/254
