### ISSUE TITLE
[Brokernode] Enforce upload size limit

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/brokernode#432]
We have a limit on webinterface, but people are uploading files from a different (homemade) client, we should also set a limit on the backend especially since oyster is paying for storage right now.

Make this configurable from `.env`

**Comment by rfornea** [comment]
This is done already.  I didn't file an issue for it, because it was an "emergency" change I had to implement, when someone made a third party client that bypassed our limit.  

Currently it checks the .env file for a limit on the total number of chunks and it rejects the upload if it has more than that.

**Comment by pzhao5** [comment]
Yep https://github.com/oysterprotocol/brokernode/blob/master/.env.test#L74
